### ISSUE TITLE
text to pdf?

### ISSUE THREAD

**Issue by Jeet1994** [ropensci/pdftools#10]
I have the following function:

```
FunctionFun <- function(.csv)
{
  sink('Dimension.txt')
  csv <- read.csv(.csv)
  dimValue <- dim(csv)
  print("The dimension of the dataset is:")
  print(dimValue)
  return(dimValue)
  sink('Dimension.txt', append=TRUE)
}
```

I want to write another function that would convert the Dimension.txt to Dimension.pdf. Can I achieve this using pdftools?

**Comment by jeroenooms** [comment]
The `pdftools` package is for *reading* pdf. To write PDF files you need to use something like knitr/markdown/latex, or the `pdf` graphics device.

**Comment by jeroenooms** [comment]
Crosspost @ http://stackoverflow.com/questions/39724362/text-to-pdf-in-r.

**Comment by Jeet1994** [comment]
Thank you. I will have a look at those you mentioned.
