### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bkumar39** [ropensci/pdftools#109]
I used pdftools package and it is working fine for me 
Please also add MIT Opensource license wordings in the package.

**Comment by jeroen** [comment]
I have added a copy of the text, but it is really not needed. The MIT license is declared in the `License` field in the package description:

https://github.com/ropensci/pdftools/blob/7967b2ffefd26e5640d65f52b4431931e083c6a5/DESCRIPTION#L10

The full text automatically gets linked from the CRAN page: https://cran.r-project.org/web/packages/pdftools/index.html. This is the only official and proper way to declare the license of an R package.
