### ISSUE TITLE
pdf_text parse consistently skips to the next page after word "Paget"

### ISSUE THREAD

**Issue by kenkoonwong** [ropensci/pdftools#118]
This is the pdf:
![image](https://user-images.githubusercontent.com/25889392/201990737-5ac39719-c888-4f12-8f22-ff6a0232af1d.png)

This is the output:
```
.\n\nEndocrinology\nDiagnose pheochromocytoma in a patient with multiple endocrine neoplasia type 2A.\nDiagnose the cause of secondary hypertension.\nEvaluate a woman for infertility.\nManage euthyroid sick syndrome.\nTreat an asymptomatic patient with 
```

I suspect it's the word "Page" that is the problem. 

I am currently using:
```
pdftools_3.3.2 
Using poppler version 22.04.0
```

**Comment by jeroen** [comment]
Can you include the pdf file so I can test it?

**Comment by kenkoonwong** [comment]
AHhh.. I realized that it was my regular expression code that cut the Paget off! I changed the code and it works just fine! Sorry for the confusion!
