### ISSUE TITLE
Ability to specify tessedit_pageseg_mode when using pdf_ocr_text

### ISSUE THREAD

**Issue by werkstattcodes** [ropensci/pdftools#121]
This is more a suggestion than an issue: 
It would be very handy if `pdf_ocr_text ` were to provide for the option to define tesseract's `tessedit_pageseg_mode`. Unless, I am mistaken this is currently not possible, and hence when needing a specific attribute value, one has to to first use `pdftools::pdf_convert` and then `tesseract::ocr(., tessedit_pageseg_mode=..)`. While these steps can be easily wrapped in one function, it would be nice if `pdf_ocr_text `would provide the option 'out of the box', particularly since the dpi and language attribute values are already forwarded.
Thank you.

**Comment by nriemenschneider** [comment]
I have got exactly the same issue. I posted my solution to the problem. Unfortunately, I am fairly new on GitHub and don't know yet how to edit the functions in R packages and add them to the official repo. I might look into this in the coming weeks or months and add 
a) the possibility two forward the options
b) the odf_ocr_two_cols function as an easy to use wrapper. 
Sidenote: the default value of tessedit_pageseg_mode is "6=block"; "1=auto+osd" The possible values can be found in tesseract:tesseract_params(filter = "tessedit_pageseg_mode").

`pdf_ocr_two_cols <- function(
    pdf, pages = NULL, dpi = 300, language = "eng", 
    options = list(tessedit_pageseg_mode = 1)) {
  # convert pdf to png
  images <- pdftools::pdf_convert(
    pdf = pdf,
    pages = pages,
    dpi = dpi)
  # define engine
  engine <- tesseract::tesseract(language = language, options = options)
  on.exit(unlink(images))
  # extract text
  vapply(X = images, FUN = tesseract::ocr, FUN.VALUE = character(1), engine = engine)
}
`
