### ISSUE TITLE
How can I get rid of two Headers which are changing every other page?

### ISSUE THREAD

**Issue by arqmain** [ropensci/pdftools#13]
Hi everyone here!

I have some problem that I cannot solve myself. I have a pdf file and I am working on it. So far, I was able to read it and I have it in my laptop.

The file has as two Headers which are changing every other page. I would like to read the file into my laptop transforming it into txt format, but get rid of the headers by the time I load it into my computer.
Would you mind giving me a help in doing it?

It is possible to do so by using “pdftools" R-projec package?
If it is not possible, do you know a way to do this one time I have it loaded in txt format in my laptop? Of course I mean using R-project.

If you want, you can get the pdf file from here: http://www.arqmain.net/Applets/Einstein-Albert-Mi-Credo-Humanista.pdf

**Comment by jeroenooms** [comment]
You can just use standard string manipulation to cut of the first two lines of each page?

```r
url <- "http://www.arqmain.net/Applets/Einstein-Albert-Mi-Credo-Humanista.pdf"
text <- pdf_text(url)
out <- sapply(text, function(page){
  lines <- strsplit(page, "\n")[[1]]
  paste(tail(lines, -2), collapse = "\n")
})
```

**Comment by arqmain** [comment]
Hi jeroenooms:

Thanks you!

It works great.

My best regards!
