### ISSUE TITLE
How to include in CRAN package

### ISSUE THREAD

**Issue by trinker** [ropensci/pdftools#15]
Great work with pdftools.  Thank you.

I recently put a package textreadr on CRAN and I get an error with solaris machines as pdftools is not available.  https://cran.r-project.org/web/checks/check_results_textreadr.html

In pdftools' checks https://cran.r-project.org/web/checks/check_results_pdftools.html I don't see solaris listed. 

- How are you able to make CRAN not check for solaris?
- How can I proceed with importing pdftools and drop the errors?

Maybe these are the same question.

**Comment by jeroenooms** [comment]
You can ignore this. It is up to CRAN to install the proper libraries needed to test the packages.

**Comment by trinker** [comment]
Thank you
