### ISSUE TITLE
Poppler-data and CJK

### ISSUE THREAD

**Issue by kochiuyu** [ropensci/pdftools#21]
Thank you for creating the package. It is excellent when working under English pdf files.

When I try to use it for pdf with Chinese (an example is attached)
[example.pdf](https://github.com/ropensci/pdftools/files/1432985/example.pdf)

I have received the following warning:

Warning: error: Missing language pack for 'Adobe-CNS1' mapping

I have tried to download standalone poppler pdftotext and try to add the library. It seems to work in the commnand. How can I add the poppler-data to the pdftools installation so that I can work in R?

Thanks.

**Comment by jeroen** [comment]
Ha I was wondering what the poppler-data files were for. I'll have a look.

**Comment by kochiuyu** [comment]
It is about encoding of pdf. 
According to the author of the package:

> This package consists of encoding files for use with poppler.  The encoding files are optional and poppler will automatically read them if they are present.  When installed, the encoding files enables  poppler to correctly render CJK and Cyrrilic properly.  While poppler is licensed under the GPL, these encoding files have different license,  and thus distributed separately.

You may see the data structure here:
https://www.archlinux.org/packages/extra/any/poppler-data/files/

**Comment by jeroen** [comment]
I don't know how to specify the path to these files if it's not the default `/usr/share/poppler/`.

**Comment by kochiuyu** [comment]
If in windows system, you can put it in the path of where you save the bin file of poppler.

What I have done is to download this zip file from the following address:
http://blog.alivate.com.au/poppler-windows/
Extract it and put it into the a folder, say, poppler.
Then it has four subfolders: bin, include, library, and share.

Then I download the poppler-data file from: https://poppler.freedesktop.org/
I extract the file and put all its content in a folder called "poppler" 
Put this new folder under share subfolder.
That is, the data files will be put into poppler/share/poppler.
For example, there is a file called CMakeList.txt.
It will be located as "poppler/share/poppler/CMakeList.txt"

Then if you use the command line (cmd) to run pdftotext on the "exmaple.pdf" that I provided. It would be okay (with some minor warnings).

**Comment by jeroen** [comment]
Right but we don't use a poppler executables because we dynamically load it as a shared library into R. So I'm not sure where it tries to look for these files then.

**Comment by kochiuyu** [comment]
Thanks for the explanation. It seems like a difficult problem.

**Comment by jeroen** [comment]
Making some progress here. So you're using Windows right?

**Comment by jeroen** [comment]
@kochiuyu I've made some changes, could you please test the devel version:

```r
devtools::install_github("ropensci/pdftools")
```

**Comment by kochiuyu** [comment]
Thank you. It works nicely. The program does not complain the problem.

It can display the Chinese character nicely.

**Comment by kochiuyu** [comment]
testinm

**Comment by jeroen** [comment]
Yes you can close it now if your problem is been addressed.

**Comment by jeroen** [comment]
This is now on CRAN.
