### ISSUE TITLE
circle symbols don't appear on the converted png

### ISSUE THREAD

**Issue by chrislad** [ropensci/pdftools#25]
The circle symbol (pch =1 or 16, 19, 20, 21) is blank or don't appear in the png when converted from a pdf.
For example:
```
pdf("baseplot.pdf")
plot(0:25, rnorm(26), type = "b", pch = 0:25, col = "red")
dev.off()
pdftools::pdf_convert("baseplot.pdf", dpi = 300, filenames = "baseplot.png")
```
![baseplot](https://user-images.githubusercontent.com/2671348/35327442-7f0f4cf8-00f1-11e8-9a4c-491d730e6bf3.png)

Plots generated by ggplot2 are also affected.

Versions: pdftools 1.5, R 3.3.3, Windows 10.

Thank you

**Comment by jeroen** [comment]
Probably dupe of https://github.com/ropensci/pdftools/issues/19

**Comment by chrislad** [comment]
Indeed!
It works with `pdf( ..., useDingbats = FALSE)` and `ggsave(..., useDingbats = FALSE)`. Your workaround with `pdf.options(useDingbats=FALSE)` is probably more robust.

Thanks!
