### ISSUE TITLE
Package zip extraction failure windows version 1.8 on CRAN

### ISSUE THREAD

**Issue by taalbrecht** [ropensci/pdftools#40]
Version of 1.8 of this package hosted on CRAN for windows that is downloaded by default using the install.package("pdftools") cannot be extracted per the error below:

Warning in install.packages :
  downloaded length 9216309 != reported length 10127221

Attempting to install from the downloaded zip file of the archive also fails as does a manual extraction of the zip file using 7zip.

The non-development version 1.8 of the package hosted on CRAN can be extracted and installed without issue.

**Comment by jeroen** [comment]
Works fine here. I guess you have an antivirus program that is corrupting the downloads.

<img width="605" alt="screen shot 2018-07-17 at 3 59 13 pm" src="https://user-images.githubusercontent.com/216319/42822078-6824d446-89da-11e8-81d9-ab8f92760966.png">

**Comment by taalbrecht** [comment]
That's exactly what it is. My company installed a man-in-the-middle intercept service (zscaler) that is corrupting the zip files. Verified it by comparing the size of the zip files downloaded on my company PC vs. downloading at home. Thanks for the response!

**Comment by jeroen** [comment]
Are you using an https mirror? Usually that prevents the mitm attack.
