### ISSUE TITLE
can pdf_data provide page's height & width?

### ISSUE THREAD

**Issue by bianchenhao** [ropensci/pdftools#49]
pdf_data's output is below,
```
# A tibble: 430 x 6
   width height     x     y space text  
          
 1    29      8   154   139 TRUE  Mazda 
 2    19      8   187   139 FALSE RX4   
 3    29      8   154   151 TRUE  Mazda 
 4    19      8   187   151 TRUE  RX4   
 5    19      8   210   151 FALSE Wag   
 6    31      8   154   163 TRUE  Datsun
 7    14      8   189   163 FALSE 710   
 8    30      8   154   176 TRUE  Hornet
 9     4      8   188   176 TRUE  4     
10    23      8   196   176 FALSE Drive 
```
however, I don't know the page's width and height.Hence, I can't transform coordinates into the percentage of the page to others. I considered using pdf_convert, but uncertain dpi, and converting pngs is slow.Can you give me some suggestions?

**Comment by jeroen** [comment]
Thanks I'll try to include that information somehow. However I found that not all pdf's reliably include this data. Some pdf's just seem to rely on the viewer to adapt the viewport to include all the content.

**Comment by bianchenhao** [comment]
> Thanks I'll try to include that information somehow. However I found that not all pdf's reliably include this data. Some pdf's just seem to rely on the viewer to adapt the viewport to include all the content.

I'm confused that how to generate x, y without info of page's height and width. I think **Relative coordinates**  of the page like percentage may be better, if anyone uses any other coordinate system.
