### ISSUE TITLE
Can provide lines' info?

### ISSUE THREAD

**Issue by bianchenhao** [ropensci/pdftools#55]
Because I want to extract tables' info, lines' info (position, width, height) are useful. For example, part of pdf below.

![image](https://user-images.githubusercontent.com/40454528/51289936-25bd4900-1a3d-11e9-8257-020368e080e2.png)

**Comment by bianchenhao** [comment]
Package tabulizer is not very accurate now, especially tables contain merged cells.

**Comment by jeroen** [comment]
Did you try the pdf_data function?

**Comment by bianchenhao** [comment]
Have tried it. My ideal procession is **1. Locating tables' position** ---> **2. Locating cells' posion** .  **pdf_data** can only provide **words' posion**, but **cells' position** is more useful which can provide info of **relationship between cells**. So, I want to use **lines' info** to do this.

**Comment by jeroen** [comment]
There are no cells in PDF, just text boxes and nicely positioned lines.

**Comment by bianchenhao** [comment]
**Line**, I mean, black lines or visible lines in the table LOL...not line 1, line2. Can provide lines' info?

**Comment by jeroen** [comment]
Mmm I think that is difficult. we could try to render to svg and maybe
extract elements that way.

**Comment by bianchenhao** [comment]
I'll try, thanks!
