### ISSUE TITLE
poppler_pdf_text not enough space

### ISSUE THREAD

**Issue by greenshare** [ropensci/pdftools#58]
I need to read a lot of pdfs. I loop through each pdf and for about 50 pdfs it works fine. Then it says poppler_pdf_text doesn't have enough space. I have deleted objects created during the loop and did gc() afterwards but it still crashes the program. Is there some other way this package is building up memory usage going through multiple pdfs?

**Comment by jeroen** [comment]
Can you include example code please

**Comment by captcoma** [comment]
@greenshare, could you solve this problem? I get the same error while looping trough pdfs...

**Comment by greenshare** [comment]
Never solved this.

Sent from my iPhone

On Apr 30, 2019, at 6:24 AM, captcoma <notifications@github.com<mailto:notifications@github.com>> wrote:


@greenshare<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_greenshare&d=DwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=xLH0h0XKzFwsmNPnIzSZSM14hi0hc2Gqr-HuKMo2ziI&m=M32-tj48H0iEx0oOo5Rn-RPsdx0U70xOsFLDbEGisi8&s=3CYqCXcofNaJ9BBKZP5POtYVL5bBCNSrmAxh_lCVfj4&e=>, could you solve this problem? I get the same error while looping trough pdfs...

**Comment by greenshare** [comment]
For each pdf in a loop I just run something like this:
library(pdftools)
for(f in 1:100){
fl<-pdf_text(fls[[f]])
rm(fl)
}
I have replicated this error with many different pdfs - get the same error.  At some point it creates the error.

**Comment by jeroen** [comment]
Moving to https://github.com/ropensci/pdftools/issues/64
