### ISSUE TITLE
Top line of pages not read in 

### ISSUE THREAD

**Issue by LaurentSmeets** [ropensci/pdftools#67]
I am reading in legislative bills from the Netherlands and for some reason when I use `pdf_text()` certain pages that have text really near to the top margin of the page are not completely read in. The top 1 or 2 rows are not recognized. if I use `pdf_data()` it does recognize these strings. 

For example first row of page 16 of [this document](https://www.tweedekamer.nl/downloads/document?id=1e8f06cd-0423-492a-b544-692b5bf75ad6&title=Voorstel%20van%20wet.pdf). What can I do to use `pdf_text()` to completely read in this file ?

**Comment by jeroen** [comment]
I've pushed a fix to make sure `pdf_text()` also includes text in the margins of the page. Can you try to install the dev version:

```r
remotes::install_github("ropensci/pdftools")
```

**Comment by jeroen** [comment]
Wij Beatrix, bij de gratie Gods, Koningin der Nederlanden, Prinses van Oranje-Nassau, enz. enz. enz. 
🤦

**Comment by LaurentSmeets** [comment]
Hi Jeroen,
Yes, this seems to solve the problem. Thanks! paramount in separating appendices from the main text in certain documents (and indeed I would love to have a long enough title that it needs to be shortened by enz. enz., enz.)
