### ISSUE TITLE
pdf_text cutting off portion of page printed in landscape

### ISSUE THREAD

**Issue by JimmyG3** [ropensci/pdftools#7]
pdf_text is not scanning in the part of the page that is past 8.5" wide.  I created an Excel and a Word doc and saved them as landscape and it is scanning entire page into R.  So, maybe it is something specific to my pdf.

**Comment by jeroenooms** [comment]
Can you include a reproducible example please?

**Comment by JimmyG3** [comment]
Unfortunately, they all have confidential info so I can't share it.  The last page of each PDF is blank and in portrait while the rest of the PDF is in landscape.  Could that cause the issue?  

I'm out of the office until Monday, when I'm back in I'll see if I can get a PDF that's suitable for sharing.

**Comment by JimmyG3** [comment]
Here's a PDF where the two columns on the far right are not being pulled into R via pdf_text.
[waurika_news_democrat.pdf](https://github.com/ropensci/pdftools/files/161587/waurika_news_democrat.pdf)

**Comment by jeroenooms** [comment]
Upstream issue: https://lists.freedesktop.org/archives/poppler/2016-March/011755.html

**Comment by jeroenooms** [comment]
Bug report: https://bugs.freedesktop.org/show_bug.cgi?id=94517

**Comment by lpatruno** [comment]
Any word on this issue?

**Comment by jeroenooms** [comment]
I don't think so, haven't heard back. You are free to subscribe to the libpoppler mailing list and post a reminder for: https://lists.freedesktop.org/archives/poppler/2016-March/011755.html

**Comment by JimmyG3** [comment]
FWIW, I have succesfully converted that PDF using Xpdf's pdftotext, which can be found here: [http://www.foolabs.com/xpdf/download.html](url)

**Comment by jeroenooms** [comment]
Looks like the poppler folks are not in a hurry to fix this, so I added a [workaround](https://github.com/ropensci/pdftools/blob/v1.0/src/bindings.cpp#L127-L131) that double the width of the target rectangle for landscape pages.

It's not perfect but I think this will avoid the problem in most cases.

**Comment by MichaelChirico** [comment]
Just encountered this again:

[voting_equipment_by_municipality_2_pdf_15114.pdf](https://github.com/ropensci/pdftools/files/629752/voting_equipment_by_municipality_2_pdf_15114.pdf)

The whole ACCESSIBLE EQUIPMENT column is clipped on all pages.

**Comment by jeroenooms** [comment]
This should be fixed in version 1.0. Can you try updating to the latest version?

**Comment by MichaelChirico** [comment]
Indeed, fixed on my example!

**Comment by JimmyG3** [comment]
That fixed my issue too!
