### ISSUE TITLE
Program Stuck with a pdf

### ISSUE THREAD

**Issue by eladbitton** [ropensci/pdftools#71]
While extracting text from this pdf:
http://ihassociation.org/wordpress/wp-content/uploads/2015/06/2014-ASHP-Handbook-web-edition.pdf

The program just gets stuck.

Reproduce:
```
import pdftotext

with open('./2014-ASHP-Handbook-web-edition.pdf', 'rb') as f:
    pdf = pdftotext.PDF(f)
text = "\n\n".join(pdf)
```

I tried to iterate through the pages and there is a specific page in which the program is stuck on.
The program is stuck and uses 100% cpu which means it keeps processing something.

If its a dependecies problem, adding timeout for processing would be good.

**Comment by jeroen** [comment]
I think you are posting this on the wrong repository. This repo is for the R package not the Python module.

**Comment by eladbitton** [comment]
My bad..
