### ISSUE TITLE
Use R.home("doc") instead of Sys.getenv("R_DOC_DIR")

### ISSUE THREAD

**Issue by BillDunlap** [ropensci/pdftools#8]
Some of the examples in pdftools use Sys.getenv("R_DOC_DIR") instead of R.home("doc") to find the documentation directory.  It looks like R_DOC_DIR is not defined by default in R-3.2.4 on Windows so the examples fail.

```
> version$platform
[1] "x86_64-w64-mingw32"
> example(pdf_info)

pdf_nf> # Just a random pdf file
pdf_nf> file.copy(file.path(Sys.getenv("R_DOC_DIR"), "NEWS.pdf"), "news.pdf")
[1] FALSE

pdf_nf> info <- pdf_info("news.pdf")
Error in normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="news.pdf": The system cannot find the file specified
```

Also, the file.copy() is not desirable, as it leaves a file behind in the current directory.
I think the example should be
   pdf_info(file.path(R.home("doc"), "NEWS.pdf"))

Bill Dunlap
wdunlap@tibco.com

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/ropensci/pdftools/commit/228cb235b79fb2db9dfd59e2da7f29b69b7ea13b. Thanks!
