### ISSUE TITLE
Pdf_data() does not find the right version of poppler, while poppler_config() does

### ISSUE THREAD

**Issue by Cdk29** [ropensci/pdftools#82]
I think it is self explanatory : 

```
> pdftools::pdf_data("~/Bureau/Abrams, M T et al 2010.pdf")
Error in poppler_pdf_data(loadfile(pdf), opw, upw) : 
  pdf_data() requires poppler >= 0.71. You have 0.41.0
> pdftools::poppler_config()
$version
[1] "0.86.1"

$can_render
[1] TRUE

$has_pdf_data
[1] FALSE

$supported_image_formats
[1] "png"  "jpeg" "jpg"  "tiff" "pnm" 
```

**Comment by Cdk29** [comment]
Solution : installing pdftools from CRAN solved the issue. I initially installed it using the following : 

install.packages("~/Bureau/pdftools/", 
                 repos = NULL, 
                 type = "source")

**Comment by jeroen** [comment]
I think you have 2 poppler installations on your machine. Either that your you upgraded poppler after installing the R package, and you need to reinstall.

**Comment by Cdk29** [comment]
No I think it was just my way of installing it that was not adequate somehow.

I tried reinstill and the issue persisted. But doing Rcpp::compile(), sudo R CMD build, and install.package() on the tar worked.
I think the issue can be closed.
