### ISSUE TITLE
Licensing issue - shouldn't this be GPL?

### ISSUE THREAD

**Issue by pedrommalaquias** [ropensci/pdftools#87]
If this tool is based / requires Poppler, shouldn't it be released under the same license (GPL2, GPL3)?

https://github.com/freedesktop/poppler
"_Note that Poppler is licensed under the GPL, not the LGPL, so programs which call Poppler must be licensed under the GPL as well. See the section History and GPL licensing for more information_."

**Comment by jeroen** [comment]
All the source code in pdftools is authored by myself, the package not include any files authored by other people. I release all of my own code as MIT (which is compatible with GPL).
