### ISSUE TITLE
Install error: ld: library not found for -ljpeg

### ISSUE THREAD

**Issue by ibagur** [ropensci/pdftools#90]
Hi, I am trying to install by compiling from source on R 4.0.3 on BigSur 11.2 and get this error:

```
ld: library not found for -ljpeg
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [qpdf.so] Error 1
ERROR: compilation failed for package `‘qpdf’```
```

I have libjpeg 9d installed via Homebrew. I tried to reinstall and re-start R with no success. No matter what, the error persists. Any suggestions? Thanks

**Comment by jeroen** [comment]
Duplicate https://github.com/ropensci/qpdf/issues/12
