### ISSUE TITLE
Error loading pdftools

### ISSUE THREAD

**Issue by pathmes** [ropensci/pdftools#94]
I get the following error message when I try `library(pdftools)`

Error: package or namespace load failed for ‘pdftools’:
 .onLoad failed in loadNamespace() for 'pdftools', details:
  call: set_poppler_data(datapath)
  error: function 'Rcpp_precious_remove' not provided by package 'Rcpp'

Tried a fresh install of pdftools and restarted R and RStudio a couple of times

**Comment by jeroen** [comment]
You need to update rcpp


Op do 15 jul. 2021 12:31 schreef Pathmeswaran ***@***.***>:

**Comment by pathmes** [comment]
Thank you for the prompt response.  Solved.
