### ISSUE TITLE
Can TOC be added？

### ISSUE THREAD

**Issue by zoushucai** [ropensci/pdftools#99]
I only see extracted TOC information from the document，but how to write TOC into PDF

**Comment by jeroen** [comment]
The pdftools package an only read pdf files, not write.

**Comment by trevorld** [comment]
@zoushucai FYI: my new work-in-progress package [{xmpdf}](https://github.com/trevorld/r-xmpdf) has a couple of functions you can use to [add pdf bookmarks aka table of contents](https://trevorldavis.com/R/xmpdf/dev/reference/bookmarks.html) to a pdf file.
